const express = require('express');
const router = express.Router();

router.post('/', (req, res) => {
  try {
    const { results } = req.body;

    if (!results) {
      return res.status(400).json({ error: 'Results data is required' });
    }

    // Generate a text report
    const reportLines = [
      '═══════════════════════════════════════════════════════════',
      '              REPLICA DETECTOR - SIMILARITY REPORT         ',
      '═══════════════════════════════════════════════════════════',
      '',
      `Date: ${new Date().toLocaleString()}`,
      `Algorithm: ${results.algorithm || 'N/A'}`,
      `Threshold: ${results.threshold || 20}%`,
      '',
      '───────────────────────────────────────────────────────────',
      '                    SIMILARITY SCORES                      ',
      '───────────────────────────────────────────────────────────',
      '',
      `Overall Similarity:    ${results.overallSimilarity || 0}%`,
      `Algorithm Similarity:  ${results.algorithmSimilarity || 0}%`,
      `N-gram Similarity:     ${results.ngramSimilarity || 0}%`,
      `Combined Score:        ${results.combinedSimilarity || 0}%`,
      '',
      `Status: ${results.similarityLevel?.label || 'N/A'}`,
      `Plagiarism Detected: ${results.isPlagiarized ? 'YES' : 'NO'}`,
      `Execution Time: ${results.executionTime || 0}ms`,
      '',
    ];

    // Matched patterns
    if (results.matches && results.matches.length > 0) {
      reportLines.push('───────────────────────────────────────────────────────────');
      reportLines.push('                    MATCHED PATTERNS                       ');
      reportLines.push('───────────────────────────────────────────────────────────');
      reportLines.push('');
      results.matches.slice(0, 20).forEach((m, i) => {
        reportLines.push(`  ${i + 1}. "${m.text}"`);
      });
      reportLines.push('');
    }

    // Sentence comparison
    if (results.sentenceComparison && results.sentenceComparison.length > 0) {
      reportLines.push('───────────────────────────────────────────────────────────');
      reportLines.push('                 SENTENCE COMPARISON                       ');
      reportLines.push('───────────────────────────────────────────────────────────');
      reportLines.push('');
      results.sentenceComparison.slice(0, 10).forEach((sc, i) => {
        reportLines.push(`  ${i + 1}. Source: "${sc.sourceSentence}"`);
        reportLines.push(`     Match:  "${sc.matchedSentence}"`);
        reportLines.push(`     Similarity: ${sc.similarity}%`);
        reportLines.push('');
      });
    }

    // Keyword matches
    if (results.keywordMatches && results.keywordMatches.length > 0) {
      reportLines.push('───────────────────────────────────────────────────────────');
      reportLines.push('                  KEYWORD MATCHES                          ');
      reportLines.push('───────────────────────────────────────────────────────────');
      reportLines.push('');
      reportLines.push(`  ${results.keywordMatches.map(k => k.word).join(', ')}`);
      reportLines.push('');
    }

    reportLines.push('═══════════════════════════════════════════════════════════');
    reportLines.push('              Generated by Replica Detector                ');
    reportLines.push('═══════════════════════════════════════════════════════════');

    const reportText = reportLines.join('\n');

    res.json({
      report: reportText,
      summary: {
        combinedSimilarity: results.combinedSimilarity || 0,
        isPlagiarized: results.isPlagiarized || false,
        matchCount: results.matchCount || 0,
        algorithm: results.algorithm || 'N/A',
        generatedAt: new Date().toISOString(),
      },
    });
  } catch (error) {
    console.error('Report error:', error);
    res.status(500).json({ error: 'Report generation failed: ' + error.message });
  }
});

module.exports = router;
